default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ln_app_development
  username: postgres
  host: db
  # url: postgresql://localhost/blog_development?pool=5

test:
  <<: *default
  database: ln_app_test

production:
  <<: *default
  database: ln_app_production
  username: ln_app
  password: <%= ENV['LN_APP_DATABASE_PASSWORD'] %>
